language: node_js
node_js:
  - lts/*

before_install:
# ssh秘钥
- openssl aes-256-cbc -K $encrypted_ee4910b28c71_key -iv $encrypted_ee4910b28c71_iv
  -in gitee_travis_key.enc -out ~/.ssh/gitee_travis_key -d
# 设置权限
- chmod 600 ~/.ssh/gitee_travis_key
- eval $(ssh-agent)
- ssh-add ~/.ssh/gitee_travis_key
script:
  - npm run docs:build
deploy:
- provider: pages:git
  # 使用v2版本的
  edge: true # opt in to dpl v2
  # Git项目
  repo: db117/db117.github.io
  # 不清理编译文件
  skip-cleanup: true
  # 目录
  local_dir: docs/.vuepress/dist
  # token
  github-token: $github
  # CNAME
  fqdn: doc.db117.top
  # 非强制
  keep-history: true
  # 用token的邮箱用户名提交
  committer_from_gh: true
  # 目标分支
  target_branch: master
- provider: script
  skip-cleanup: true
  script: bash deployToGitee.sh $giteePassword
# ssh
addons:
  ssh_known_hosts:
  - github.com
  - gitee.com