language: node_js
node_js:
  - lts/*
script:
  - npm run docs:build
  - npm run cname
deploy:
  provider: pages
  repo: db117/db117.github.io
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: $github
  keep-history: true
  email: z351622948@163.com
  on:
    branch: master